[package]
name = "helium-app"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.31.1"
egui = "0.31.1"
egui_extras = { version = "0.31.1", features = ["all_loaders"] }
egui_plot = "0.32.1"
image = "0.25.6"
chrono = "0.4.38"

[dependencies.helium-core]
path = "../helium-core"

[dependencies.helium-api]
path = "../helium-api"